# Generated by Django 4.0 on 2021-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.TextField(max_length=100)),
                ('foreign_id', models.TextField(max_length=100)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('date_joined', models.DateField()),
                ('date_of_birth', models.DateField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
